# Generated by Django 5.1.7 on 2025-03-11 01:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Package_tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="message",
            field=models.CharField(
                choices=[
                    ("billing_information_received", "Billing Information Received"),
                    ("origin_scan", "Origin Scan"),
                    ("departure_scan", "Departure Scan"),
                    ("arrival_scan", "Arrival Scan"),
                    ("out_for_dilivery", "Out For Dilivery"),
                    ("delivered", "Delivered"),
                ],
                default="processing",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="receiver_location",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="package",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("pre-transit", "pre-transit"),
                    ("in_transit", "In Transit"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
    ]
